# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
defaults:
  run:
    working-directory: app

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install keras networkx numpy opencv-python PyQt5 PyQt5-Qt5 PyQt5-sip PyQt5-stubs qtwidgets requests scikit-learn scipy tensorboard tensorboard-data-server tensorflow tensorflow-estimator tensorflow-intel tensorflow-io-gcs-filesystem termcolor threadpoolctl torchy matplotlib
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev
    - name: Install Qt platform plugins
      run: |
        sudo apt-get update
        sudo apt-get install -y libqt5gui5 libqt5widgets5 libqt5core5a libqt5dbus5 qtbase5-dev
        sudo apt-get install -y libqt5gui5-dev libqt5widgets5-dev libqt5core5-dev libqt5dbus5-dev
        sudo apt-get install -y libxcb1 libxcb1-dev
    - name: Run PyQt5 app
      run: |
        python Main.py
